# External gems
# See http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html for making `jekyll archives` work.
gems:
  - jekyll-archives # Sorry, not GitHub pages friendly!
  - jekyll-sitemap
  - jekyll-paginate

exclude:
  - "/vendor/"

# Site settings
title: YeongRong's Blog
subtitle: "Interested in Data Science using R and Python"
email: yeongrong.bak@gmail.com
name: YeongRong Bak
description: >
  Interested in Data Science using R and Python.
# Base URL of site (i.e. /blog). It should always start with a slash,
# and never end with a slash. Set it to a blank value if hosting at the
# root of your server.
baseurl: 
url: "http://yeongrongbak.github.io" # the base hostname & protocol for your site
cover: "/assets/header_image.jpg"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: false
highlightjs_theme: "monokai-sublime"

# Archive settings (see https://github.com/jekyll/jekyll-archives/)
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

# Disqus comments
disqus_shortname: yeongrong

# Google analytics
ga_tracking_id: "UA-123263237-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: Story
    desc: "Any story about me"

  - cat: MachineLearning
    desc: "About ML Algorithm"

  - cat: DeepLearning
    desc: "About DL Algorithm"
        
  - cat: R&Python
    desc: "R and Python programming for data analysis"
  
  - cat: Lecture
    desc: "Summary of my study"

  - cat: Visualization
    desc: "About Data Visualization"

  - cat: DataCompetition
    desc: "Big data competition that I participated so far"

  - cat: Issue
    desc: "Issue and situation about data science industry"

  - cat: Database
    desc: "About database using SQL"



# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# Example:
#
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: true                           # Include in the "Share" section of posts
social:
  - name: Facebook
    icon: facebook
    username: yeongrongbak
    url:
    desc: Friend me on Facebook
    share: true

  - name: GitHub
    icon: github
    username: yeongrongbak
    url: https://github.com/yeongrongbak
    desc: Fork me on GitHub
    share: true

  - name: LinkedIn
    icon: linkedin
    username: Yeongrong Bak
    url: https://www.linkedin.com/in/%EC%98%81%EB%A1%B1-%EB%B0%95-1088ba102
    desc: Connect with me on LinkedIn
    share: false

  - name: Google+
    icon: google-plus
    username:
    url:
    desc: Add me to your Circles
    share: true

  - name: Instagram
    icon: instagram
    username:
    url:
    desc: Follow me on Instagram
    share: false

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "/assets/logo.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"

    twitter_image: "/assets/logo.png"

    os_repo: "https://github.com/bencentra/centrarium.com"
    os_rcs_type: "git"
    os_src: "git@github.com:bencentra/centrarium.com.git"

theme: jekyll-theme-minimal
